// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(ui_screen_t screen)
{
    lv_disp_t * dispp = lv_display_get_default();

    lv_theme_t * theme = lv_theme_default_init(dispp,
                                               lv_palette_main(LV_PALETTE_BLUE),
                                               lv_palette_main(LV_PALETTE_RED),
                                               false,
                                               LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    ui_TouchScreen_screen_init();
    ui_DispScreen_screen_init();
    ui_Disp2Screen_screen_init();
    ui_LoudScreen_screen_init();
    ui_MicScreen_screen_init();
    ui_Sensor1Screen_screen_init();
    ui_Sensor2Screen_screen_init();
    ui_FinalScreen_screen_init();

    ui____initial_actions0 = lv_obj_create(NULL);

    switch(screen) {
        case SCREEN_TOUCH:
            lv_disp_load_scr(ui_TouchScreen);
            break;
        case SCREEN_FINAL:
            lv_disp_load_scr(ui_FinalScreen);
            break;
        default:
            lv_disp_load_scr(ui_TouchScreen);
            break;
    }
}

void ui_destroy(void)
{
    ui_TouchScreen_screen_destroy();
    ui_DispScreen_screen_destroy();
    ui_Disp2Screen_screen_destroy();
    ui_LoudScreen_screen_destroy();
    ui_MicScreen_screen_destroy();
    ui_Sensor1Screen_screen_destroy();
    ui_Sensor2Screen_screen_destroy();
    ui_FinalScreen_screen_destroy();
}
