// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef _ESP_C5_FIRMWARE_UI_H
#define _ESP_C5_FIRMWARE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_TouchScreen.h"
#include "screens/ui_DispScreen.h"
#include "screens/ui_Disp2Screen.h"
#include "screens/ui_LoudScreen.h"
#include "screens/ui_MicScreen.h"
#include "screens/ui_Sensor1Screen.h"
#include "screens/ui_Sensor2Screen.h"
#include "screens/ui_FinalScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_loudspeaker_png);    // assets/loudspeaker.png
LV_IMG_DECLARE(ui_img_mic_png);    // assets/mic.png

// FONTS
LV_FONT_DECLARE(ui_font_Heiti14);
LV_FONT_DECLARE(ui_font_Heiti16);
LV_FONT_DECLARE(ui_font_Heiti20);

//选择初始化屏幕
typedef enum {
    SCREEN_TOUCH,
    SCREEN_FINAL
} ui_screen_t;

// UI INIT
void ui_init(ui_screen_t screen);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
