// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <inttypes.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "errno.h"
#include "sdkconfig.h"
#include "esp_log.h"
#include "esp_err.h"
#include "nvs_flash.h"
#include "nvs.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/event_groups.h"

#define NVS_PART_NAME      "nvs"
#define NVS_PART_NAMESPACE "test_result"

extern bool g_first_test;
extern bool at_sensor2_screen;

typedef enum {
    APP_UI_EVENT_MIC_START = BIT(0),
    APP_UI_EVENT_IMU_START = BIT(1),
    APP_UI_EVENT_SPEAKER_START = BIT(2),
    APP_UI_EVENT_CHANGE_SPEAKER = BIT(3),
    APP_UI_EVENT_SPEAKER_STOP = BIT(4),
    APP_UI_EVENT_CHANGE_MIC = BIT(5),
    APP_UI_EVENT_SENSOR_BMI270_BMM350_TEST = BIT(6),
    APP_UI_EVENT_RADER_TEST_START = BIT(7),
    APP_UI_EVENT_MB_TEST_OVER = BIT(8),
    APP_UI_EVENT_DOCK_TEST_OVER = BIT(9),
    APP_UI_EVENT_BRACKET_TEST_OVER = BIT(10),
    APP_UI_EVENT_SENSOR_BMM680_TEST = BIT(11),
} app_ui_event_type_t;

void Clicked_result(lv_event_t * e);
void Switch_color(lv_event_t * e);
void Start_loudspeaker(lv_event_t * e);
void Change_loudspeaker(lv_event_t * e);
void Stop_loudspeaker(lv_event_t * e);
void Init_microphone(lv_event_t * e);
void Change_mic(lv_event_t * e);
void Check_sensor(lv_event_t * e);
void Check_sensor2(lv_event_t * e);
void Touch_pass(lv_event_t * e);
void Check_result(lv_event_t * e);
void Display_pass(lv_event_t * e);
void Display_fail(lv_event_t * e);
void Loudspeaker_pass(lv_event_t * e);
void Loudspeaker_fail(lv_event_t * e);
void Mic_pass(lv_event_t * e);
void Mic_fail(lv_event_t * e);
void Sensor1_pass(lv_event_t * e);
void Sensor1_fail(lv_event_t * e);
void Sensor2_pass(lv_event_t * e);
void Sensor2_fail(lv_event_t * e);
void Rst_flash(lv_event_t * e);

esp_err_t ui_event_init(void);
EventBits_t ui_event_wait_events(void);

void flash_write_init(void);
void flash_write_state(char* key, char* value);
uint8_t flash_read_state(char* key);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
