// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <inttypes.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <errno.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/event_groups.h"
#include "sdkconfig.h"
#include "esp_log.h"
#include "esp_err.h"

typedef enum {
    APP_UI_EVENT_MIC_START = BIT(0),
    APP_UI_EVENT_SPEAKER_START = BIT(1),
    APP_UI_EVENT_CHANGE_SPEAKER = BIT(2),
    APP_UI_EVENT_SPEAKER_STOP = BIT(3),
    APP_UI_EVENT_CHANGE_MIC = BIT(4),
    APP_UI_EVENT_SENSOR_BMI270_BMM350_TEST = BIT(5),
    APP_UI_EVENT_SENSOR_BME680_TEST = BIT(6),
} app_ui_event_type_t;

bool get_first_test(void);
void set_first_test(bool first_test);
bool get_at_sensor2_screen(void);
void set_at_sensor2_screen(bool at_sensor2);
void Clicked_result(lv_event_t * e);
void Switch_color(lv_event_t * e);
void Start_loudspeaker(lv_event_t * e);
void Change_loudspeaker(lv_event_t * e);
void Stop_loudspeaker(lv_event_t * e);
void Init_microphone(lv_event_t * e);
void Change_mic(lv_event_t * e);
void Check_sensor(lv_event_t * e);
void Check_sensor2(lv_event_t * e);
void Touch_pass(lv_event_t * e);
void Check_result(lv_event_t * e);
void Display_pass(lv_event_t * e);
void Display_fail(lv_event_t * e);
void Loudspeaker_pass(lv_event_t * e);
void Loudspeaker_fail(lv_event_t * e);
void Mic_pass(lv_event_t * e);
void Mic_fail(lv_event_t * e);
void Sensor1_pass(lv_event_t * e);
void Sensor1_fail(lv_event_t * e);
void Sensor2_pass(lv_event_t * e);
void Sensor2_fail(lv_event_t * e);
void Rst_flash(lv_event_t * e);

esp_err_t ui_event_init(void);
EventBits_t ui_event_wait_events(void);

void flash_write_init(void);
void flash_write_state(char* key, char* value);
uint8_t flash_read_state(char* key);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
