// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "esp_check.h"
#include "ui.h"
#include "ui_events.h"
#include "flash.h"

static uint8_t clicked_times = 0;
lv_timer_t * scrColorSwitchTask = NULL;
lv_timer_t * arcDecayTask = NULL;
static EventGroupHandle_t event_grp = NULL;

static const char *TAG = "ui_event";

bool g_first_test = true;
bool at_sensor2_screen = false;

bool get_first_test(void)
{
    return g_first_test;
}

void set_first_test(bool first_test)
{
    g_first_test = first_test;
}

bool get_at_sensor2_screen(void)
{
    return at_sensor2_screen;
}

void set_at_sensor2_screen(bool at_sensor2)
{
    at_sensor2_screen = at_sensor2;
}

esp_err_t ui_event_init(void)
{
    event_grp = xEventGroupCreate();
    ESP_RETURN_ON_FALSE(event_grp, ESP_ERR_NO_MEM, TAG, "event group init failed");

    return ESP_OK;
}

EventBits_t ui_event_wait_events(void)
{
    ESP_RETURN_ON_FALSE(event_grp, ESP_ERR_INVALID_STATE, TAG, "event group don't init");

    // EventBits_t event_bits = NULL;
    return xEventGroupWaitBits(event_grp, APP_UI_EVENT_MIC_START | APP_UI_EVENT_SPEAKER_START | APP_UI_EVENT_CHANGE_SPEAKER
                                | APP_UI_EVENT_SPEAKER_STOP | APP_UI_EVENT_CHANGE_MIC | APP_UI_EVENT_SENSOR_BMI270_BMM350_TEST
                                | APP_UI_EVENT_SENSOR_BME680_TEST, pdTRUE, pdFALSE, portMAX_DELAY);
}

void Clicked_result(lv_event_t * e)
{
	// Your code here
	clicked_times++;
    if(clicked_times == 1) {
        lv_obj_set_x(ui_TouchTestBtn, 100);
        lv_obj_set_y(ui_TouchTestBtn, -70);
    }
    else if(clicked_times == 2) {
        lv_obj_set_x(ui_TouchTestBtn, -100);
        lv_obj_set_y(ui_TouchTestBtn, 70);
    }
    else if(clicked_times == 3) {
        lv_obj_set_x(ui_TouchTestBtn, 100);
        lv_obj_set_y(ui_TouchTestBtn, 70);
    }
    else if(clicked_times == 4) {
        lv_obj_add_flag(ui_TouchTestBtn, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_TouchPanel, LV_OBJ_FLAG_HIDDEN);
        clicked_times = 0;
    }
}

static void setDispScrColor()
{
    static uint8_t colorState = 0;
    colorState++;
    if(colorState == 1) {
        lv_label_set_text(ui_Disp2ColorLab, "绿");
        lv_obj_set_style_bg_color(ui_Disp2Screen, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else if(colorState == 2) {
        lv_label_set_text(ui_Disp2ColorLab, "蓝");
        lv_obj_set_style_bg_color(ui_Disp2Screen, lv_color_hex(0x0000ff), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else if(colorState == 3) {
        lv_obj_set_style_bg_color(ui_Disp2Screen, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_clear_flag(ui_Disp2Panel, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_Disp2ColorLab, LV_OBJ_FLAG_HIDDEN);
        lv_timer_del(scrColorSwitchTask);
        colorState = 0;
    }
}

static void setArcDecayColor()
{
    static uint8_t arc_val = 100;
    arc_val -= 5;
    if(arc_val <= 0) {
        arc_val = 0;
        lv_timer_del(arcDecayTask);
        lv_obj_add_flag(ui_Arc1, LV_OBJ_FLAG_HIDDEN);
        lv_label_set_text(ui_Label7, "播放中");
        lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xEFBF10), LV_PART_MAIN | LV_STATE_DEFAULT);
        arc_val = 100;
    }else{
        lv_arc_set_value(ui_Arc1, arc_val);
    }
}

void Switch_color(lv_event_t * e)
{
	scrColorSwitchTask = lv_timer_create(setDispScrColor, 1000, 0);
    lv_timer_set_repeat_count(scrColorSwitchTask,3);
}

void Start_loudspeaker(lv_event_t * e)
{
	ESP_LOGI("UI", "Begin LoudSpeaker");
	xEventGroupSetBits(event_grp, APP_UI_EVENT_SPEAKER_START);
}

void Change_loudspeaker(lv_event_t * e)
{
	ESP_LOGI("UI", "Change LoudSpeaker");
	xEventGroupSetBits(event_grp, APP_UI_EVENT_CHANGE_SPEAKER);
}

void Stop_loudspeaker(lv_event_t * e)
{
	ESP_LOGI("UI", "Stop LoudSpeaker");
	xEventGroupSetBits(event_grp, APP_UI_EVENT_SPEAKER_STOP);
}

void Init_microphone(lv_event_t * e)
{
	ESP_LOGI("UI", "Init Microphone");
	xEventGroupSetBits(event_grp, APP_UI_EVENT_MIC_START);
}

void Change_mic(lv_event_t * e)
{
	ESP_LOGI("UI", "Change Microphone");
	xEventGroupSetBits(event_grp, APP_UI_EVENT_CHANGE_MIC);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_HIDDEN); 
    arcDecayTask = lv_timer_create(setArcDecayColor, 150, NULL);
    lv_timer_set_repeat_count(arcDecayTask,20);
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_CLICKABLE);
}

void Check_sensor(lv_event_t * e)
{
	ESP_LOGI("UI", "Check Sensor");
	xEventGroupSetBits(event_grp, APP_UI_EVENT_SENSOR_BME680_TEST);
}

void Check_sensor2(lv_event_t * e)
{
	ESP_LOGI("UI", "Check Sensor2");
    at_sensor2_screen = true;
	xEventGroupSetBits(event_grp, APP_UI_EVENT_SENSOR_BMI270_BMM350_TEST);
}

void Check_result(lv_event_t * e)
{
    if(flash_read_state("touch") == 1) {
        lv_obj_set_style_text_color(ui_ResVal1, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal1, "正常");
    }
    else if(flash_read_state("touch") == 2) {
        lv_obj_set_style_text_color(ui_ResVal1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal1, "异常");
    }
    else {
        lv_obj_set_style_text_color(ui_ResVal1, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal1, "待检");
    }
    if(flash_read_state("display") == 1) {
        lv_obj_set_style_text_color(ui_ResVal2, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal2, "正常");
    }
    else if(flash_read_state("display") == 2) {
        lv_obj_set_style_text_color(ui_ResVal2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal2, "异常");
    }
    else {
        lv_obj_set_style_text_color(ui_ResVal2, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal2, "待检");
    }
    if(flash_read_state("loudspeaker") == 1) {
        lv_obj_set_style_text_color(ui_ResVal3, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal3, "正常");
    }
    else if(flash_read_state("loudspeaker") == 2) {
        lv_obj_set_style_text_color(ui_ResVal3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal3, "异常");
    }
    else {
        lv_obj_set_style_text_color(ui_ResVal3, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal3, "待检");
    }
    if(flash_read_state("mic") == 1) {
        lv_obj_set_style_text_color(ui_ResVal5, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal5, "正常");
    }
    else if(flash_read_state("mic") == 2) {
        lv_obj_set_style_text_color(ui_ResVal5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal5, "异常");
    }
    else {
        lv_obj_set_style_text_color(ui_ResVal5, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal5, "待检");
    }
    if(flash_read_state("sensor1") == 1) {
        lv_obj_set_style_text_color(ui_ResVal6, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal6, "正常");
    }
    else if(flash_read_state("sensor1") == 2) {
        lv_obj_set_style_text_color(ui_ResVal6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal6, "异常");
    }
    else {
        lv_obj_set_style_text_color(ui_ResVal6, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal6, "待检");
    }
    if(flash_read_state("sensor2") == 1) {
        lv_obj_set_style_text_color(ui_ResVal7, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal7, "正常");
    }
    else if(flash_read_state("sensor2") == 2) {
        lv_obj_set_style_text_color(ui_ResVal7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal7, "异常");
    }
    else {
        lv_obj_set_style_text_color(ui_ResVal7, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_ResVal7, "待检");
    }
}

void Touch_pass(lv_event_t * e)
{
    flash_write_state("touch","pass");
}

void Display_pass(lv_event_t * e)
{
    flash_write_state("display","pass");
}

void Display_fail(lv_event_t * e)
{
    flash_write_state("display","fail");
}

void Loudspeaker_pass(lv_event_t * e)
{
    flash_write_state("loudspeaker","pass");
}

void Loudspeaker_fail(lv_event_t * e)
{
    flash_write_state("loudspeaker","fail");
}

void Mic_pass(lv_event_t * e)
{
    flash_write_state("mic","pass");
}

void Mic_fail(lv_event_t * e)
{
    flash_write_state("mic","fail");
}

void Sensor1_pass(lv_event_t * e)
{
    flash_write_state("sensor1","pass");
}

void Sensor1_fail(lv_event_t * e)
{
    flash_write_state("sensor1","fail");
}

void Sensor2_pass(lv_event_t * e)
{
    flash_write_state("sensor2","pass");
}

void Sensor2_fail(lv_event_t * e)
{
    flash_write_state("sensor2","fail");
}

void Rst_flash(lv_event_t * e)
{
    flash_write_state("touch","");
    flash_write_state("display","");
    flash_write_state("loudspeaker","");
    flash_write_state("mic","");
    flash_write_state("sensor1","");
    flash_write_state("sensor2","");
    Check_result(e);
    g_first_test = true;
}