// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "../ui.h"

lv_obj_t * ui_Disp2Screen = NULL;
lv_obj_t * ui_Disp2Panel = NULL;
lv_obj_t * ui_Disp2Lab = NULL;
lv_obj_t * ui_Disp2YesBtn = NULL;
lv_obj_t * ui_Disp2YesLab = NULL;
lv_obj_t * ui_Disp2NoBtn = NULL;
lv_obj_t * ui_Disp2NoLab = NULL;
lv_obj_t * ui_Disp2ColorLab = NULL;
// event funtions
void ui_event_Disp2YesBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Display_pass(e);
        if (g_first_test) {
            _ui_screen_change(&ui_LoudScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_LoudScreen_screen_init);
            Start_loudspeaker(e);
        } else {
            Check_result(e);
            _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FinalScreen_screen_init);  
        }
    }
}

void ui_event_Disp2NoBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Display_fail(e);
        if(g_first_test) {
            _ui_screen_change(&ui_LoudScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_LoudScreen_screen_init);
            Start_loudspeaker(e);
        } else {
            Check_result(e);
            _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FinalScreen_screen_init);  
        }
    }
}

// build funtions

void ui_Disp2Screen_screen_init(void)
{
    ui_Disp2Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Disp2Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Disp2Screen, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Disp2Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Disp2Panel = lv_obj_create(ui_Disp2Screen);
    lv_obj_set_width(ui_Disp2Panel, 240);
    lv_obj_set_height(ui_Disp2Panel, 186);
    lv_obj_set_align(ui_Disp2Panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Disp2Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Disp2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Disp2Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Disp2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Disp2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Disp2Lab = lv_label_create(ui_Disp2Panel);
    lv_obj_set_width(ui_Disp2Lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disp2Lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disp2Lab, 0);
    lv_obj_set_y(ui_Disp2Lab, -42);
    lv_obj_set_align(ui_Disp2Lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Disp2Lab, "屏幕显示是否正常？");
    lv_obj_set_style_text_color(ui_Disp2Lab, lv_color_hex(0x1292ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disp2Lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disp2Lab, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Disp2YesBtn = lv_button_create(ui_Disp2Panel);
    lv_obj_set_width(ui_Disp2YesBtn, 60);
    lv_obj_set_height(ui_Disp2YesBtn, 40);
    lv_obj_set_x(ui_Disp2YesBtn, 60);
    lv_obj_set_y(ui_Disp2YesBtn, 30);
    lv_obj_set_align(ui_Disp2YesBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Disp2YesBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Disp2YesBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Disp2YesLab = lv_label_create(ui_Disp2YesBtn);
    lv_obj_set_width(ui_Disp2YesLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disp2YesLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Disp2YesLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Disp2YesLab, "是");
    lv_obj_set_style_text_font(ui_Disp2YesLab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Disp2NoBtn = lv_button_create(ui_Disp2Panel);
    lv_obj_set_width(ui_Disp2NoBtn, 60);
    lv_obj_set_height(ui_Disp2NoBtn, 40);
    lv_obj_set_x(ui_Disp2NoBtn, -60);
    lv_obj_set_y(ui_Disp2NoBtn, 30);
    lv_obj_set_align(ui_Disp2NoBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Disp2NoBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Disp2NoBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Disp2NoLab = lv_label_create(ui_Disp2NoBtn);
    lv_obj_set_width(ui_Disp2NoLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disp2NoLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Disp2NoLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Disp2NoLab, "否");
    lv_obj_set_style_text_font(ui_Disp2NoLab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Disp2ColorLab = lv_label_create(ui_Disp2Screen);
    lv_obj_set_width(ui_Disp2ColorLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disp2ColorLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Disp2ColorLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Disp2ColorLab, "红");
    lv_obj_set_style_text_color(ui_Disp2ColorLab, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disp2ColorLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disp2ColorLab, &ui_font_Heiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Disp2YesBtn, ui_event_Disp2YesBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Disp2NoBtn, ui_event_Disp2NoBtn, LV_EVENT_ALL, NULL);

}

void ui_Disp2Screen_screen_destroy(void)
{
    if(ui_Disp2Screen) lv_obj_del(ui_Disp2Screen);

    // NULL screen variables
    ui_Disp2Screen = NULL;
    ui_Disp2Panel = NULL;
    ui_Disp2Lab = NULL;
    ui_Disp2YesBtn = NULL;
    ui_Disp2YesLab = NULL;
    ui_Disp2NoBtn = NULL;
    ui_Disp2NoLab = NULL;
    ui_Disp2ColorLab = NULL;

}
