// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_DISPSCREEN_H
#define UI_DISPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DispScreen
extern void ui_DispScreen_screen_init(void);
extern void ui_DispScreen_screen_destroy(void);
extern lv_obj_t * ui_DispScreen;
extern lv_obj_t * ui_DispTitleLab;
extern lv_obj_t * ui_DispTipLab;
extern void ui_event_DispNextBtn(lv_event_t * e);
extern lv_obj_t * ui_DispNextBtn;
extern lv_obj_t * ui_DispNextLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

