// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "../ui.h"

lv_obj_t * ui_DispScreen = NULL;
lv_obj_t * ui_DispTitleLab = NULL;
lv_obj_t * ui_DispTipLab = NULL;
lv_obj_t * ui_DispNextBtn = NULL;
lv_obj_t * ui_DispNextLab = NULL;
// event funtions
void ui_event_DispNextBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        ui_Disp2Screen_screen_init();
        _ui_screen_change(&ui_Disp2Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Disp2Screen_screen_init);
        Switch_color(e);
    }
}

// build funtions

void ui_DispScreen_screen_init(void)
{
    ui_DispScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DispScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DispTitleLab = lv_label_create(ui_DispScreen);
    lv_obj_set_width(ui_DispTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DispTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DispTitleLab, 0);
    lv_obj_set_y(ui_DispTitleLab, -86);
    lv_obj_set_align(ui_DispTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DispTitleLab, "屏幕显示测试");
    lv_obj_set_style_text_color(ui_DispTitleLab, lv_color_hex(0x1292ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DispTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DispTitleLab, &ui_font_Heiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DispTipLab = lv_label_create(ui_DispScreen);
    lv_obj_set_width(ui_DispTipLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DispTipLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DispTipLab, 0);
    lv_obj_set_y(ui_DispTipLab, -39);
    lv_obj_set_align(ui_DispTipLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DispTipLab,
                      "点击<开始>按钮，屏幕将依次全屏显示\n“红-绿-蓝”三种颜色，请观察屏幕显示\n是否正常！");
    lv_obj_set_style_text_color(ui_DispTipLab, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DispTipLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DispTipLab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DispNextBtn = lv_button_create(ui_DispScreen);
    lv_obj_set_width(ui_DispNextBtn, 100);
    lv_obj_set_height(ui_DispNextBtn, 40);
    lv_obj_set_x(ui_DispNextBtn, 0);
    lv_obj_set_y(ui_DispNextBtn, 53);
    lv_obj_set_align(ui_DispNextBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DispNextBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DispNextBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DispNextLab = lv_label_create(ui_DispNextBtn);
    lv_obj_set_width(ui_DispNextLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DispNextLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DispNextLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DispNextLab, "开始");
    lv_obj_set_style_text_font(ui_DispNextLab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DispNextBtn, ui_event_DispNextBtn, LV_EVENT_ALL, NULL);

}

void ui_DispScreen_screen_destroy(void)
{
    if(ui_DispScreen) lv_obj_del(ui_DispScreen);

    // NULL screen variables
    ui_DispScreen = NULL;
    ui_DispTitleLab = NULL;
    ui_DispTipLab = NULL;
    ui_DispNextBtn = NULL;
    ui_DispNextLab = NULL;

}
