// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_DISP2SCREEN_H
#define UI_DISP2SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Disp2Screen
extern void ui_Disp2Screen_screen_init(void);
extern void ui_Disp2Screen_screen_destroy(void);
extern lv_obj_t * ui_Disp2Screen;
extern lv_obj_t * ui_Disp2Panel;
extern lv_obj_t * ui_Disp2Lab;
extern void ui_event_Disp2YesBtn(lv_event_t * e);
extern lv_obj_t * ui_Disp2YesBtn;
extern lv_obj_t * ui_Disp2YesLab;
extern void ui_event_Disp2NoBtn(lv_event_t * e);
extern lv_obj_t * ui_Disp2NoBtn;
extern lv_obj_t * ui_Disp2NoLab;
extern lv_obj_t * ui_Disp2ColorLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

