// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_FINALSCREEN_H
#define UI_FINALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FinalScreen
extern void ui_FinalScreen_screen_init(void);
extern void ui_FinalScreen_screen_destroy(void);
extern lv_obj_t * ui_FinalScreen;
extern lv_obj_t * ui_Sensor2TitleLab2;
extern lv_obj_t * ui_ResPanel1;
extern lv_obj_t * ui_ResLab1;
extern lv_obj_t * ui_ResVal1;
extern lv_obj_t * ui_ResPanel2;
extern lv_obj_t * ui_ResLab2;
extern lv_obj_t * ui_ResVal2;
extern lv_obj_t * ui_ResPanel3;
extern lv_obj_t * ui_ResLab3;
extern lv_obj_t * ui_ResVal3;
extern lv_obj_t * ui_ResPanel5;
extern lv_obj_t * ui_ResLab5;
extern lv_obj_t * ui_ResVal5;
extern lv_obj_t * ui_ResPanel6;
extern lv_obj_t * ui_ResLab6;
extern lv_obj_t * ui_ResVal6;
extern lv_obj_t * ui_ResPanel7;
extern lv_obj_t * ui_ResLab7;
extern lv_obj_t * ui_ResVal7;
extern lv_obj_t * ui_RstBtn;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

