// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "../ui.h"

lv_obj_t * ui_FinalScreen = NULL;
lv_obj_t * ui_Sensor2TitleLab2 = NULL;
lv_obj_t * ui_ResPanel1 = NULL;
lv_obj_t * ui_ResLab1 = NULL;
lv_obj_t * ui_ResVal1 = NULL;
lv_obj_t * ui_ResPanel2 = NULL;
lv_obj_t * ui_ResLab2 = NULL;
lv_obj_t * ui_ResVal2 = NULL;
lv_obj_t * ui_ResPanel3 = NULL;
lv_obj_t * ui_ResLab3 = NULL;
lv_obj_t * ui_ResVal3 = NULL;
lv_obj_t * ui_ResPanel5 = NULL;
lv_obj_t * ui_ResLab5 = NULL;
lv_obj_t * ui_ResVal5 = NULL;
lv_obj_t * ui_ResPanel6 = NULL;
lv_obj_t * ui_ResLab6 = NULL;
lv_obj_t * ui_ResVal6 = NULL;
lv_obj_t * ui_ResPanel7 = NULL;
lv_obj_t * ui_ResLab7 = NULL;
lv_obj_t * ui_ResVal7 = NULL;
lv_obj_t * ui_RstBtn = NULL;
lv_obj_t * ui_Label25 = NULL;
// event funtions
void ui_event_ResPanel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        ui_TouchScreen_screen_init();
        _ui_screen_change(&ui_TouchScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_TouchScreen_screen_init);
    }
}

void ui_event_ResPanel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        ui_DispScreen_screen_init();
        _ui_screen_change(&ui_DispScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_DispScreen_screen_init);
    }
}

void ui_event_ResPanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        ui_LoudScreen_screen_init();
        Start_loudspeaker(e);
        _ui_screen_change(&ui_LoudScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_LoudScreen_screen_init);
    }
}

void ui_event_ResPanel5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Init_microphone(e);
        ui_MicScreen_screen_init();
        _ui_screen_change(&ui_MicScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MicScreen_screen_init);
    }
}

void ui_event_ResPanel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Check_sensor(e);
        _ui_screen_change(&ui_Sensor1Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Sensor1Screen_screen_init);
    }
}

void ui_event_ResPanel7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Check_sensor2(e);
        _ui_screen_change(&ui_Sensor2Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Sensor2Screen_screen_init);
    }
}

void ui_event_RstBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Rst_flash(e);
    }
}

// build funtions

void ui_FinalScreen_screen_init(void)
{
    ui_FinalScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_FinalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sensor2TitleLab2 = lv_label_create(ui_FinalScreen);
    lv_obj_set_width(ui_Sensor2TitleLab2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Sensor2TitleLab2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Sensor2TitleLab2, 0);
    lv_obj_set_y(ui_Sensor2TitleLab2, -90);
    lv_obj_set_align(ui_Sensor2TitleLab2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Sensor2TitleLab2, "测试结果");
    lv_obj_set_style_text_color(ui_Sensor2TitleLab2, lv_color_hex(0x1292ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Sensor2TitleLab2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Sensor2TitleLab2, &ui_font_Heiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResPanel1 = lv_obj_create(ui_FinalScreen);
    lv_obj_set_width(ui_ResPanel1, 80);
    lv_obj_set_height(ui_ResPanel1, 68);
    lv_obj_set_x(ui_ResPanel1, -90);
    lv_obj_set_y(ui_ResPanel1, -30);
    lv_obj_set_align(ui_ResPanel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResPanel1, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResPanel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResLab1 = lv_label_create(ui_ResPanel1);
    lv_obj_set_width(ui_ResLab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResLab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResLab1, 0);
    lv_obj_set_y(ui_ResLab1, -15);
    lv_obj_set_align(ui_ResLab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResLab1, "屏幕触控");
    lv_obj_set_style_text_font(ui_ResLab1, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResVal1 = lv_label_create(ui_ResPanel1);
    lv_obj_set_width(ui_ResVal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResVal1, 0);
    lv_obj_set_y(ui_ResVal1, 15);
    lv_obj_set_align(ui_ResVal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResVal1, "正常");
    lv_obj_set_style_text_color(ui_ResVal1, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResVal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResVal1, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResPanel2 = lv_obj_create(ui_FinalScreen);
    lv_obj_set_width(ui_ResPanel2, 80);
    lv_obj_set_height(ui_ResPanel2, 68);
    lv_obj_set_x(ui_ResPanel2, 0);
    lv_obj_set_y(ui_ResPanel2, -30);
    lv_obj_set_align(ui_ResPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResPanel2, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResPanel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResLab2 = lv_label_create(ui_ResPanel2);
    lv_obj_set_width(ui_ResLab2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResLab2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResLab2, 0);
    lv_obj_set_y(ui_ResLab2, -15);
    lv_obj_set_align(ui_ResLab2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResLab2, "屏幕显示");
    lv_obj_set_style_text_font(ui_ResLab2, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResVal2 = lv_label_create(ui_ResPanel2);
    lv_obj_set_width(ui_ResVal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResVal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResVal2, 0);
    lv_obj_set_y(ui_ResVal2, 15);
    lv_obj_set_align(ui_ResVal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResVal2, "异常");
    lv_obj_set_style_text_color(ui_ResVal2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResVal2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResVal2, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResPanel3 = lv_obj_create(ui_FinalScreen);
    lv_obj_set_width(ui_ResPanel3, 80);
    lv_obj_set_height(ui_ResPanel3, 68);
    lv_obj_set_x(ui_ResPanel3, 90);
    lv_obj_set_y(ui_ResPanel3, -30);
    lv_obj_set_align(ui_ResPanel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResPanel3, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResPanel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResLab3 = lv_label_create(ui_ResPanel3);
    lv_obj_set_width(ui_ResLab3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResLab3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResLab3, 0);
    lv_obj_set_y(ui_ResLab3, -15);
    lv_obj_set_align(ui_ResLab3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResLab3, "扬声器");
    lv_obj_set_style_text_font(ui_ResLab3, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResVal3 = lv_label_create(ui_ResPanel3);
    lv_obj_set_width(ui_ResVal3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResVal3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResVal3, 0);
    lv_obj_set_y(ui_ResVal3, 15);
    lv_obj_set_align(ui_ResVal3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResVal3, "正常");
    lv_obj_set_style_text_color(ui_ResVal3, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResVal3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResVal3, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResPanel5 = lv_obj_create(ui_FinalScreen);
    lv_obj_set_width(ui_ResPanel5, 80);
    lv_obj_set_height(ui_ResPanel5, 68);
    lv_obj_set_x(ui_ResPanel5, -90);
    lv_obj_set_y(ui_ResPanel5, 50);
    lv_obj_set_align(ui_ResPanel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResPanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResPanel5, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResPanel5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResLab5 = lv_label_create(ui_ResPanel5);
    lv_obj_set_width(ui_ResLab5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResLab5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResLab5, 0);
    lv_obj_set_y(ui_ResLab5, -15);
    lv_obj_set_align(ui_ResLab5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResLab5, "麦克风");
    lv_obj_set_style_text_font(ui_ResLab5, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResVal5 = lv_label_create(ui_ResPanel5);
    lv_obj_set_width(ui_ResVal5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResVal5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResVal5, 0);
    lv_obj_set_y(ui_ResVal5, 15);
    lv_obj_set_align(ui_ResVal5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResVal5, "正常");
    lv_obj_set_style_text_color(ui_ResVal5, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResVal5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResVal5, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResPanel6 = lv_obj_create(ui_FinalScreen);
    lv_obj_set_width(ui_ResPanel6, 80);
    lv_obj_set_height(ui_ResPanel6, 68);
    lv_obj_set_x(ui_ResPanel6, 0);
    lv_obj_set_y(ui_ResPanel6, 50);
    lv_obj_set_align(ui_ResPanel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResPanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResPanel6, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResPanel6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResPanel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResLab6 = lv_label_create(ui_ResPanel6);
    lv_obj_set_width(ui_ResLab6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResLab6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResLab6, 0);
    lv_obj_set_y(ui_ResLab6, -15);
    lv_obj_set_align(ui_ResLab6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResLab6, "传感器1");
    lv_obj_set_style_text_font(ui_ResLab6, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResVal6 = lv_label_create(ui_ResPanel6);
    lv_obj_set_width(ui_ResVal6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResVal6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResVal6, 0);
    lv_obj_set_y(ui_ResVal6, 15);
    lv_obj_set_align(ui_ResVal6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResVal6, "待检");
    lv_obj_set_style_text_color(ui_ResVal6, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResVal6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResVal6, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResPanel7 = lv_obj_create(ui_FinalScreen);
    lv_obj_set_width(ui_ResPanel7, 80);
    lv_obj_set_height(ui_ResPanel7, 68);
    lv_obj_set_x(ui_ResPanel7, 90);
    lv_obj_set_y(ui_ResPanel7, 50);
    lv_obj_set_align(ui_ResPanel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResPanel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResPanel7, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResPanel7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResPanel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResLab7 = lv_label_create(ui_ResPanel7);
    lv_obj_set_width(ui_ResLab7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResLab7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResLab7, 0);
    lv_obj_set_y(ui_ResLab7, -15);
    lv_obj_set_align(ui_ResLab7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResLab7, "传感器2");
    lv_obj_set_style_text_font(ui_ResLab7, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResVal7 = lv_label_create(ui_ResPanel7);
    lv_obj_set_width(ui_ResVal7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResVal7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResVal7, 0);
    lv_obj_set_y(ui_ResVal7, 15);
    lv_obj_set_align(ui_ResVal7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResVal7, "正常");
    lv_obj_set_style_text_color(ui_ResVal7, lv_color_hex(0x175F11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResVal7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResVal7, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RstBtn = lv_button_create(ui_FinalScreen);
    lv_obj_set_width(ui_RstBtn, 60);
    lv_obj_set_height(ui_RstBtn, 30);
    lv_obj_set_x(ui_RstBtn, 80);
    lv_obj_set_y(ui_RstBtn, -91);
    lv_obj_set_align(ui_RstBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RstBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RstBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_RstBtn);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "重置");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ResPanel1, ui_event_ResPanel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResPanel2, ui_event_ResPanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResPanel3, ui_event_ResPanel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResPanel5, ui_event_ResPanel5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResPanel6, ui_event_ResPanel6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResPanel7, ui_event_ResPanel7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RstBtn, ui_event_RstBtn, LV_EVENT_ALL, NULL);

}

void ui_FinalScreen_screen_destroy(void)
{
    if(ui_FinalScreen) lv_obj_del(ui_FinalScreen);

    // NULL screen variables
    ui_FinalScreen = NULL;
    ui_Sensor2TitleLab2 = NULL;
    ui_ResPanel1 = NULL;
    ui_ResLab1 = NULL;
    ui_ResVal1 = NULL;
    ui_ResPanel2 = NULL;
    ui_ResLab2 = NULL;
    ui_ResVal2 = NULL;
    ui_ResPanel3 = NULL;
    ui_ResLab3 = NULL;
    ui_ResVal3 = NULL;
    ui_ResPanel5 = NULL;
    ui_ResLab5 = NULL;
    ui_ResVal5 = NULL;
    ui_ResPanel6 = NULL;
    ui_ResLab6 = NULL;
    ui_ResVal6 = NULL;
    ui_ResPanel7 = NULL;
    ui_ResLab7 = NULL;
    ui_ResVal7 = NULL;
    ui_RstBtn = NULL;
    ui_Label25 = NULL;

}
