// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "../ui.h"

lv_obj_t * ui_LoudScreen = NULL;
lv_obj_t * ui_LoudTitleLab = NULL;
lv_obj_t * ui_LoudTipLab = NULL;
lv_obj_t * ui_LoudImg = NULL;
lv_obj_t * ui_LoudYesBtn = NULL;
lv_obj_t * ui_LoudYesLab = NULL;
lv_obj_t * ui_LoudNoBtn = NULL;
lv_obj_t * ui_LoudNoLab = NULL;
// event funtions
void ui_event_LoudImg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Change_loudspeaker(e);
    }
}

void ui_event_LoudYesBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {        
        Loudspeaker_pass(e);
        Stop_loudspeaker(e);
        if(get_first_test()) {
            ui_MicScreen_screen_init();
            _ui_screen_change(&ui_MicScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MicScreen_screen_init);
            Init_microphone(e);
        } else {
            Check_result(e);
            _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FinalScreen_screen_init);  
        }
    }
}

void ui_event_LoudNoBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        Loudspeaker_fail(e);
        Stop_loudspeaker(e);
        if (get_first_test()) {
            ui_MicScreen_screen_init();
            _ui_screen_change(&ui_MicScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MicScreen_screen_init);
            Init_microphone(e);
        } else {
            Check_result(e);
            _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FinalScreen_screen_init);  
        }
    }
}

// build funtions

void ui_LoudScreen_screen_init(void)
{
    ui_LoudScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LoudScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoudTitleLab = lv_label_create(ui_LoudScreen);
    lv_obj_set_width(ui_LoudTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoudTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoudTitleLab, 0);
    lv_obj_set_y(ui_LoudTitleLab, -86);
    lv_obj_set_align(ui_LoudTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoudTitleLab, "扬声器测试");
    lv_obj_set_style_text_color(ui_LoudTitleLab, lv_color_hex(0x1292ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoudTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoudTitleLab, &ui_font_Heiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoudTipLab = lv_label_create(ui_LoudScreen);
    lv_obj_set_width(ui_LoudTipLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoudTipLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoudTipLab, 0);
    lv_obj_set_y(ui_LoudTipLab, -50);
    lv_obj_set_align(ui_LoudTipLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoudTipLab, "点击下方播放按钮，\n观察扬声器播放是否正常？");
    lv_obj_set_style_text_color(ui_LoudTipLab, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoudTipLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LoudTipLab, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoudTipLab, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoudImg = lv_image_create(ui_LoudScreen);
    lv_image_set_src(ui_LoudImg, &ui_img_loudspeaker_png);
    lv_obj_set_width(ui_LoudImg, 50);
    lv_obj_set_height(ui_LoudImg, 50);
    lv_obj_set_align(ui_LoudImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoudImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LoudImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_LoudImg, 64);

    ui_LoudYesBtn = lv_button_create(ui_LoudScreen);
    lv_obj_set_width(ui_LoudYesBtn, 60);
    lv_obj_set_height(ui_LoudYesBtn, 40);
    lv_obj_set_x(ui_LoudYesBtn, 60);
    lv_obj_set_y(ui_LoudYesBtn, 50);
    lv_obj_set_align(ui_LoudYesBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoudYesBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LoudYesBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoudYesLab = lv_label_create(ui_LoudYesBtn);
    lv_obj_set_width(ui_LoudYesLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoudYesLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LoudYesLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoudYesLab, "是");
    lv_obj_set_style_text_font(ui_LoudYesLab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoudNoBtn = lv_button_create(ui_LoudScreen);
    lv_obj_set_width(ui_LoudNoBtn, 60);
    lv_obj_set_height(ui_LoudNoBtn, 40);
    lv_obj_set_x(ui_LoudNoBtn, -60);
    lv_obj_set_y(ui_LoudNoBtn, 50);
    lv_obj_set_align(ui_LoudNoBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoudNoBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LoudNoBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoudNoLab = lv_label_create(ui_LoudNoBtn);
    lv_obj_set_width(ui_LoudNoLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoudNoLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LoudNoLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoudNoLab, "否");
    lv_obj_set_style_text_font(ui_LoudNoLab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LoudImg, ui_event_LoudImg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoudYesBtn, ui_event_LoudYesBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoudNoBtn, ui_event_LoudNoBtn, LV_EVENT_ALL, NULL);

}

void ui_LoudScreen_screen_destroy(void)
{
    if(ui_LoudScreen) lv_obj_del(ui_LoudScreen);

    // NULL screen variables
    ui_LoudScreen = NULL;
    ui_LoudTitleLab = NULL;
    ui_LoudTipLab = NULL;
    ui_LoudImg = NULL;
    ui_LoudYesBtn = NULL;
    ui_LoudYesLab = NULL;
    ui_LoudNoBtn = NULL;
    ui_LoudNoLab = NULL;

}
