// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_LOUDSCREEN_H
#define UI_LOUDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LoudScreen
extern void ui_LoudScreen_screen_init(void);
extern void ui_LoudScreen_screen_destroy(void);
extern lv_obj_t * ui_LoudScreen;
extern lv_obj_t * ui_LoudTitleLab;
extern lv_obj_t * ui_LoudTipLab;
extern void ui_event_LoudImg(lv_event_t * e);
extern lv_obj_t * ui_LoudImg;
extern void ui_event_LoudYesBtn(lv_event_t * e);
extern lv_obj_t * ui_LoudYesBtn;
extern lv_obj_t * ui_LoudYesLab;
extern void ui_event_LoudNoBtn(lv_event_t * e);
extern lv_obj_t * ui_LoudNoBtn;
extern lv_obj_t * ui_LoudNoLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

