// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "../ui.h"

lv_obj_t * ui_MicScreen = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_MicPanel = NULL;
lv_obj_t * ui_MicLab2 = NULL;
lv_obj_t * ui_MicBtn3 = NULL;
lv_obj_t * ui_MicBtnLab3 = NULL;
lv_obj_t * ui_MicBtn4 = NULL;
lv_obj_t * ui_MicBtnLab4 = NULL;
lv_obj_t * ui_Arc1 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Change_mic(e);
    }
        
}

void ui_event_MicBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Mic_fail(e);
        if (g_first_test) {
            _ui_screen_change(&ui_Sensor1Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Sensor1Screen_screen_init);
            Check_sensor(e);
        } else {
            Check_result(e);
            _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FinalScreen_screen_init);  
        }
    }
}

void ui_event_MicBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Mic_pass(e);
        if (g_first_test) {
            _ui_screen_change(&ui_Sensor1Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Sensor1Screen_screen_init);
            Check_sensor(e);
        } else {
            Check_result(e);
            _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FinalScreen_screen_init);  
        }
    }
}

// build funtions

void ui_MicScreen_screen_init(void)
{
    ui_MicScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_MicScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -86);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "麦克风测试");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x1292ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Heiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_MicScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -48);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6,
                      "点击<录音>按钮将录制2秒音频，\n录制完成后扬声器将自动播放音频");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_MicScreen);
    lv_image_set_src(ui_Image3, &ui_img_mic_png);
    lv_obj_set_width(ui_Image3, 50);
    lv_obj_set_height(ui_Image3, 50);
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, 20);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 64);

    ui_Button2 = lv_button_create(ui_MicScreen);
    lv_obj_set_width(ui_Button2, 120);
    lv_obj_set_height(ui_Button2, 40);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, 80);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    ui_Label7 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "录音");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MicPanel = lv_obj_create(ui_MicScreen);
    lv_obj_set_width(ui_MicPanel, 244);
    lv_obj_set_height(ui_MicPanel, 133);
    lv_obj_set_x(ui_MicPanel, 0);
    lv_obj_set_y(ui_MicPanel, 41);
    lv_obj_set_align(ui_MicPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MicPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_MicPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MicPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MicPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MicPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MicLab2 = lv_label_create(ui_MicPanel);
    lv_obj_set_width(ui_MicLab2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MicLab2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MicLab2, 0);
    lv_obj_set_y(ui_MicLab2, -20);
    lv_obj_set_align(ui_MicLab2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MicLab2, "麦克风是否正常");
    lv_obj_set_style_text_color(ui_MicLab2, lv_color_hex(0xEFA512), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MicLab2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MicLab2, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MicBtn3 = lv_button_create(ui_MicPanel);
    lv_obj_set_width(ui_MicBtn3, 60);
    lv_obj_set_height(ui_MicBtn3, 40);
    lv_obj_set_x(ui_MicBtn3, -60);
    lv_obj_set_y(ui_MicBtn3, 30);
    lv_obj_set_align(ui_MicBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MicBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MicBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MicBtnLab3 = lv_label_create(ui_MicBtn3);
    lv_obj_set_width(ui_MicBtnLab3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MicBtnLab3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MicBtnLab3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MicBtnLab3, "否");
    lv_obj_set_style_text_font(ui_MicBtnLab3, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MicBtn4 = lv_button_create(ui_MicPanel);
    lv_obj_set_width(ui_MicBtn4, 60);
    lv_obj_set_height(ui_MicBtn4, 40);
    lv_obj_set_x(ui_MicBtn4, 60);
    lv_obj_set_y(ui_MicBtn4, 30);
    lv_obj_set_align(ui_MicBtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MicBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MicBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MicBtnLab4 = lv_label_create(ui_MicBtn4);
    lv_obj_set_width(ui_MicBtnLab4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MicBtnLab4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MicBtnLab4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MicBtnLab4, "是");
    lv_obj_set_style_text_font(ui_MicBtnLab4, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_MicScreen);
    lv_obj_set_width(ui_Arc1, 80);
    lv_obj_set_height(ui_Arc1, 80);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, 19);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 100);
    lv_obj_set_style_arc_width(ui_Arc1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_side(ui_Arc1, LV_BORDER_SIDE_BOTTOM, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_Arc1, LV_OBJ_FLAG_HIDDEN); 

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MicBtn3, ui_event_MicBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MicBtn4, ui_event_MicBtn4, LV_EVENT_ALL, NULL);

}

void ui_MicScreen_screen_destroy(void)
{
    if(ui_MicScreen) lv_obj_del(ui_MicScreen);

    // NULL screen variables
    ui_MicScreen = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Image3 = NULL;
    ui_Button2 = NULL;
    ui_Label7 = NULL;
    ui_MicPanel = NULL;
    ui_MicLab2 = NULL;
    ui_MicBtn3 = NULL;
    ui_MicBtnLab3 = NULL;
    ui_MicBtn4 = NULL;
    ui_MicBtnLab4 = NULL;
    ui_Arc1 = NULL;

}
