// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_MICSCREEN_H
#define UI_MICSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MicScreen
extern void ui_MicScreen_screen_init(void);
extern void ui_MicScreen_screen_destroy(void);
extern lv_obj_t * ui_MicScreen;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image3;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_MicPanel;
extern lv_obj_t * ui_MicLab2;
extern void ui_event_MicBtn3(lv_event_t * e);
extern lv_obj_t * ui_MicBtn3;
extern lv_obj_t * ui_MicBtnLab3;
extern void ui_event_MicBtn4(lv_event_t * e);
extern lv_obj_t * ui_MicBtn4;
extern lv_obj_t * ui_MicBtnLab4;
extern lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

