// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_SENSOR1SCREEN_H
#define UI_SENSOR1SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Sensor1Screen
extern void ui_Sensor1Screen_screen_init(void);
extern void ui_Sensor1Screen_screen_destroy(void);
extern lv_obj_t * ui_Sensor1Screen;
extern lv_obj_t * ui_Sensor1TitleLab;
extern lv_obj_t * ui_Sensor1TipLab;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label24;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

