// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "../ui.h"

lv_obj_t * ui_Sensor2Screen = NULL;
lv_obj_t * ui_Sensor2TitleLab = NULL;
lv_obj_t * ui_AccPanel = NULL;
lv_obj_t * ui_AccTitle = NULL;
lv_obj_t * ui_AccStatus = NULL;
lv_obj_t * ui_AccXLab = NULL;
lv_obj_t * ui_AccXVal = NULL;
lv_obj_t * ui_AccYLab = NULL;
lv_obj_t * ui_AccYVal = NULL;
lv_obj_t * ui_AccZLab = NULL;
lv_obj_t * ui_AccZVal = NULL;
lv_obj_t * ui_GyroPanel = NULL;
lv_obj_t * ui_GyroTitle = NULL;
lv_obj_t * ui_GyroStatus = NULL;
lv_obj_t * ui_GyroXLab1 = NULL;
lv_obj_t * ui_GyroXVal1 = NULL;
lv_obj_t * ui_GyroYLab1 = NULL;
lv_obj_t * ui_GyroYVal1 = NULL;
lv_obj_t * ui_GyroZLab1 = NULL;
lv_obj_t * ui_GyroZVal1 = NULL;
lv_obj_t * ui_MagPanel = NULL;
lv_obj_t * ui_MagTitle = NULL;
lv_obj_t * ui_MagStatus = NULL;
lv_obj_t * ui_MagXLab = NULL;
lv_obj_t * ui_MagXVal = NULL;
lv_obj_t * ui_MagYLab = NULL;
lv_obj_t * ui_MagYVal = NULL;
lv_obj_t * ui_MagZLab = NULL;
lv_obj_t * ui_MagZVal = NULL;
lv_obj_t * ui_Sensor2Tip = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label27 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_FinalScreen_screen_init);
        Check_result(e);
        g_first_test = false;
        at_sensor2_screen = false;
    }
}

// build funtions

void ui_Sensor2Screen_screen_init(void)
{
    ui_Sensor2Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Sensor2Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sensor2TitleLab = lv_label_create(ui_Sensor2Screen);
    lv_obj_set_width(ui_Sensor2TitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Sensor2TitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Sensor2TitleLab, -50);
    lv_obj_set_y(ui_Sensor2TitleLab, -90);
    lv_obj_set_align(ui_Sensor2TitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Sensor2TitleLab, "BMI270+BMM350");
    lv_obj_set_style_text_color(ui_Sensor2TitleLab, lv_color_hex(0x1292ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Sensor2TitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Sensor2TitleLab, &ui_font_Heiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccPanel = lv_obj_create(ui_Sensor2Screen);
    lv_obj_set_width(ui_AccPanel, 90);
    lv_obj_set_height(ui_AccPanel, 130);
    lv_obj_set_x(ui_AccPanel, -95);
    lv_obj_set_y(ui_AccPanel, 20);
    lv_obj_set_align(ui_AccPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AccPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AccPanel, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AccPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccTitle = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccTitle, 0);
    lv_obj_set_y(ui_AccTitle, -48);
    lv_obj_set_align(ui_AccTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccTitle, "加速度计");
    lv_obj_set_style_text_font(ui_AccTitle, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccStatus = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccStatus, 0);
    lv_obj_set_y(ui_AccStatus, -25);
    lv_obj_set_align(ui_AccStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccStatus, "待检");
    lv_obj_set_style_text_color(ui_AccStatus, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AccStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AccStatus, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccXLab = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccXLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccXLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccXLab, -20);
    lv_obj_set_y(ui_AccXLab, -5);
    lv_obj_set_align(ui_AccXLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccXLab, "AccX");

    ui_AccXVal = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccXVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccXVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccXVal, 23);
    lv_obj_set_y(ui_AccXVal, -5);
    lv_obj_set_align(ui_AccXVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccXVal, "0");
    lv_obj_set_style_text_color(ui_AccXVal, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AccXVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccYLab = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccYLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccYLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccYLab, -20);
    lv_obj_set_y(ui_AccYLab, 20);
    lv_obj_set_align(ui_AccYLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccYLab, "AccY");

    ui_AccYVal = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccYVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccYVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccYVal, 23);
    lv_obj_set_y(ui_AccYVal, 20);
    lv_obj_set_align(ui_AccYVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccYVal, "0");
    lv_obj_set_style_text_color(ui_AccYVal, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AccYVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccZLab = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccZLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccZLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccZLab, -20);
    lv_obj_set_y(ui_AccZLab, 45);
    lv_obj_set_align(ui_AccZLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccZLab, "AccZ");

    ui_AccZVal = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccZVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccZVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccZVal, 23);
    lv_obj_set_y(ui_AccZVal, 45);
    lv_obj_set_align(ui_AccZVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccZVal, "0");
    lv_obj_set_style_text_color(ui_AccZVal, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AccZVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GyroPanel = lv_obj_create(ui_Sensor2Screen);
    lv_obj_set_width(ui_GyroPanel, 90);
    lv_obj_set_height(ui_GyroPanel, 130);
    lv_obj_set_x(ui_GyroPanel, 0);
    lv_obj_set_y(ui_GyroPanel, 20);
    lv_obj_set_align(ui_GyroPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GyroPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GyroPanel, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GyroPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GyroPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GyroTitle = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroTitle, 0);
    lv_obj_set_y(ui_GyroTitle, -48);
    lv_obj_set_align(ui_GyroTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroTitle, "角速度计");
    lv_obj_set_style_text_font(ui_GyroTitle, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GyroStatus = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroStatus, 0);
    lv_obj_set_y(ui_GyroStatus, -25);
    lv_obj_set_align(ui_GyroStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroStatus, "待检");
    lv_obj_set_style_text_color(ui_GyroStatus, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GyroStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GyroStatus, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GyroXLab1 = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroXLab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroXLab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroXLab1, -20);
    lv_obj_set_y(ui_GyroXLab1, -5);
    lv_obj_set_align(ui_GyroXLab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroXLab1, "GyroX");

    ui_GyroXVal1 = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroXVal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroXVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroXVal1, 23);
    lv_obj_set_y(ui_GyroXVal1, -5);
    lv_obj_set_align(ui_GyroXVal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroXVal1, "0");
    lv_obj_set_style_text_color(ui_GyroXVal1, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GyroXVal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GyroYLab1 = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroYLab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroYLab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroYLab1, -20);
    lv_obj_set_y(ui_GyroYLab1, 20);
    lv_obj_set_align(ui_GyroYLab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroYLab1, "GyroY");

    ui_GyroYVal1 = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroYVal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroYVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroYVal1, 23);
    lv_obj_set_y(ui_GyroYVal1, 20);
    lv_obj_set_align(ui_GyroYVal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroYVal1, "0");
    lv_obj_set_style_text_color(ui_GyroYVal1, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GyroYVal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GyroZLab1 = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroZLab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroZLab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroZLab1, -20);
    lv_obj_set_y(ui_GyroZLab1, 45);
    lv_obj_set_align(ui_GyroZLab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroZLab1, "GyroZ");

    ui_GyroZVal1 = lv_label_create(ui_GyroPanel);
    lv_obj_set_width(ui_GyroZVal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroZVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroZVal1, 23);
    lv_obj_set_y(ui_GyroZVal1, 45);
    lv_obj_set_align(ui_GyroZVal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GyroZVal1, "0");
    lv_obj_set_style_text_color(ui_GyroZVal1, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GyroZVal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagPanel = lv_obj_create(ui_Sensor2Screen);
    lv_obj_set_width(ui_MagPanel, 90);
    lv_obj_set_height(ui_MagPanel, 130);
    lv_obj_set_x(ui_MagPanel, 95);
    lv_obj_set_y(ui_MagPanel, 20);
    lv_obj_set_align(ui_MagPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MagPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MagPanel, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MagPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MagPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagTitle = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagTitle, 0);
    lv_obj_set_y(ui_MagTitle, -48);
    lv_obj_set_align(ui_MagTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagTitle, "磁力计");
    lv_obj_set_style_text_font(ui_MagTitle, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagStatus = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagStatus, 0);
    lv_obj_set_y(ui_MagStatus, -25);
    lv_obj_set_align(ui_MagStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagStatus, "待检");
    lv_obj_set_style_text_color(ui_MagStatus, lv_color_hex(0x1969E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MagStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MagStatus, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagXLab = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagXLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagXLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagXLab, -20);
    lv_obj_set_y(ui_MagXLab, -5);
    lv_obj_set_align(ui_MagXLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagXLab, "MagX");

    ui_MagXVal = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagXVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagXVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagXVal, 23);
    lv_obj_set_y(ui_MagXVal, -5);
    lv_obj_set_align(ui_MagXVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagXVal, "0");
    lv_obj_set_style_text_color(ui_MagXVal, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MagXVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagYLab = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagYLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagYLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagYLab, -20);
    lv_obj_set_y(ui_MagYLab, 20);
    lv_obj_set_align(ui_MagYLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagYLab, "MagY");

    ui_MagYVal = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagYVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagYVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagYVal, 23);
    lv_obj_set_y(ui_MagYVal, 20);
    lv_obj_set_align(ui_MagYVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagYVal, "0");
    lv_obj_set_style_text_color(ui_MagYVal, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MagYVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagZLab = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagZLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagZLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagZLab, -20);
    lv_obj_set_y(ui_MagZLab, 45);
    lv_obj_set_align(ui_MagZLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagZLab, "MagZ");

    ui_MagZVal = lv_label_create(ui_MagPanel);
    lv_obj_set_width(ui_MagZVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagZVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MagZVal, 23);
    lv_obj_set_y(ui_MagZVal, 45);
    lv_obj_set_align(ui_MagZVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagZVal, "0");
    lv_obj_set_style_text_color(ui_MagZVal, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MagZVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sensor2Tip = lv_label_create(ui_Sensor2Screen);
    lv_obj_set_width(ui_Sensor2Tip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Sensor2Tip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Sensor2Tip, 0);
    lv_obj_set_y(ui_Sensor2Tip, -62);
    lv_obj_set_align(ui_Sensor2Tip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Sensor2Tip, "传感器初始化中");
    lv_obj_set_style_text_color(ui_Sensor2Tip, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Sensor2Tip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Sensor2Tip, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_Sensor2Screen);
    lv_obj_set_width(ui_Button4, 80);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_x(ui_Button4, 80);
    lv_obj_set_y(ui_Button4, -90);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "下一项");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Sensor2Screen_screen_destroy(void)
{
    if(ui_Sensor2Screen) lv_obj_del(ui_Sensor2Screen);

    // NULL screen variables
    ui_Sensor2Screen = NULL;
    ui_Sensor2TitleLab = NULL;
    ui_AccPanel = NULL;
    ui_AccTitle = NULL;
    ui_AccStatus = NULL;
    ui_AccXLab = NULL;
    ui_AccXVal = NULL;
    ui_AccYLab = NULL;
    ui_AccYVal = NULL;
    ui_AccZLab = NULL;
    ui_AccZVal = NULL;
    ui_GyroPanel = NULL;
    ui_GyroTitle = NULL;
    ui_GyroStatus = NULL;
    ui_GyroXLab1 = NULL;
    ui_GyroXVal1 = NULL;
    ui_GyroYLab1 = NULL;
    ui_GyroYVal1 = NULL;
    ui_GyroZLab1 = NULL;
    ui_GyroZVal1 = NULL;
    ui_MagPanel = NULL;
    ui_MagTitle = NULL;
    ui_MagStatus = NULL;
    ui_MagXLab = NULL;
    ui_MagXVal = NULL;
    ui_MagYLab = NULL;
    ui_MagYVal = NULL;
    ui_MagZLab = NULL;
    ui_MagZVal = NULL;
    ui_Sensor2Tip = NULL;
    ui_Button4 = NULL;
    ui_Label27 = NULL;

}
