// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_SENSOR2SCREEN_H
#define UI_SENSOR2SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Sensor2Screen
extern void ui_Sensor2Screen_screen_init(void);
extern void ui_Sensor2Screen_screen_destroy(void);
extern lv_obj_t * ui_Sensor2Screen;
extern lv_obj_t * ui_Sensor2TitleLab;
extern lv_obj_t * ui_AccPanel;
extern lv_obj_t * ui_AccTitle;
extern lv_obj_t * ui_AccStatus;
extern lv_obj_t * ui_AccXLab;
extern lv_obj_t * ui_AccXVal;
extern lv_obj_t * ui_AccYLab;
extern lv_obj_t * ui_AccYVal;
extern lv_obj_t * ui_AccZLab;
extern lv_obj_t * ui_AccZVal;
extern lv_obj_t * ui_GyroPanel;
extern lv_obj_t * ui_GyroTitle;
extern lv_obj_t * ui_GyroStatus;
extern lv_obj_t * ui_GyroXLab1;
extern lv_obj_t * ui_GyroXVal1;
extern lv_obj_t * ui_GyroYLab1;
extern lv_obj_t * ui_GyroYVal1;
extern lv_obj_t * ui_GyroZLab1;
extern lv_obj_t * ui_GyroZVal1;
extern lv_obj_t * ui_MagPanel;
extern lv_obj_t * ui_MagTitle;
extern lv_obj_t * ui_MagStatus;
extern lv_obj_t * ui_MagXLab;
extern lv_obj_t * ui_MagXVal;
extern lv_obj_t * ui_MagYLab;
extern lv_obj_t * ui_MagYVal;
extern lv_obj_t * ui_MagZLab;
extern lv_obj_t * ui_MagZVal;
extern lv_obj_t * ui_Sensor2Tip;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

