// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#include "../ui.h"

lv_obj_t * ui_TouchScreen = NULL;
lv_obj_t * ui_TouchTitlelab = NULL;
lv_obj_t * ui_TouchTiplab = NULL;
lv_obj_t * ui_TouchPanel = NULL;
lv_obj_t * ui_TouchSuclab = NULL;
lv_obj_t * ui_TouchNextbtn = NULL;
lv_obj_t * ui_TouchNextlab = NULL;
lv_obj_t * ui_TouchTestBtn = NULL;
lv_obj_t * ui_TouchTestLab = NULL;
// event funtions
void ui_event_TouchNextbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Touch_pass(e);
        if(g_first_test) {
            _ui_screen_change(&ui_DispScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_DispScreen_screen_init);
        } else {
            Check_result(e);
            _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FinalScreen_screen_init);
        }

    }
}

void ui_event_TouchTestBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Clicked_result(e);
    }
}

// build funtions

void ui_TouchScreen_screen_init(void)
{
    ui_TouchScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TouchScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TouchTitlelab = lv_label_create(ui_TouchScreen);
    lv_obj_set_width(ui_TouchTitlelab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TouchTitlelab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TouchTitlelab, 0);
    lv_obj_set_y(ui_TouchTitlelab, -80);
    lv_obj_set_align(ui_TouchTitlelab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TouchTitlelab, "屏幕触控测试");
    lv_obj_set_style_text_color(ui_TouchTitlelab, lv_color_hex(0x1292ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TouchTitlelab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TouchTitlelab, &ui_font_Heiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchTiplab = lv_label_create(ui_TouchScreen);
    lv_obj_set_width(ui_TouchTiplab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TouchTiplab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TouchTiplab, 0);
    lv_obj_set_y(ui_TouchTiplab, -40);
    lv_obj_set_align(ui_TouchTiplab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TouchTiplab, "请点击屏幕按钮\n完成测试!");
    lv_obj_set_style_text_color(ui_TouchTiplab, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TouchTiplab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TouchTiplab, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TouchTiplab, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchPanel = lv_obj_create(ui_TouchScreen);
    lv_obj_set_width(ui_TouchPanel, 120);
    lv_obj_set_height(ui_TouchPanel, 106);
    lv_obj_set_x(ui_TouchPanel, 0);
    lv_obj_set_y(ui_TouchPanel, 35);
    lv_obj_set_align(ui_TouchPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TouchPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_TouchPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TouchPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TouchPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TouchPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchSuclab = lv_label_create(ui_TouchPanel);
    lv_obj_set_width(ui_TouchSuclab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TouchSuclab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TouchSuclab, 0);
    lv_obj_set_y(ui_TouchSuclab, -22);
    lv_obj_set_align(ui_TouchSuclab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TouchSuclab, "屏幕触控正常");
    lv_obj_set_style_text_color(ui_TouchSuclab, lv_color_hex(0xEFA512), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TouchSuclab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TouchSuclab, &ui_font_Heiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchNextbtn = lv_button_create(ui_TouchPanel);
    lv_obj_set_width(ui_TouchNextbtn, 100);
    lv_obj_set_height(ui_TouchNextbtn, 40);
    lv_obj_set_x(ui_TouchNextbtn, 0);
    lv_obj_set_y(ui_TouchNextbtn, 25);
    lv_obj_set_align(ui_TouchNextbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TouchNextbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TouchNextbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TouchNextlab = lv_label_create(ui_TouchNextbtn);
    lv_obj_set_width(ui_TouchNextlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TouchNextlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TouchNextlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TouchNextlab, "下一项");
    lv_obj_set_style_text_font(ui_TouchNextlab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchTestBtn = lv_button_create(ui_TouchScreen);
    lv_obj_set_width(ui_TouchTestBtn, 60);
    lv_obj_set_height(ui_TouchTestBtn, 60);
    lv_obj_set_x(ui_TouchTestBtn, -100);
    lv_obj_set_y(ui_TouchTestBtn, -70);
    lv_obj_set_align(ui_TouchTestBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TouchTestBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TouchTestBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TouchTestBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchTestLab = lv_label_create(ui_TouchTestBtn);
    lv_obj_set_width(ui_TouchTestLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TouchTestLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TouchTestLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TouchTestLab, "点我");
    lv_obj_set_style_text_font(ui_TouchTestLab, &ui_font_Heiti14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TouchNextbtn, ui_event_TouchNextbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TouchTestBtn, ui_event_TouchTestBtn, LV_EVENT_ALL, NULL);

}

void ui_TouchScreen_screen_destroy(void)
{
    if(ui_TouchScreen) lv_obj_del(ui_TouchScreen);

    // NULL screen variables
    ui_TouchScreen = NULL;
    ui_TouchTitlelab = NULL;
    ui_TouchTiplab = NULL;
    ui_TouchPanel = NULL;
    ui_TouchSuclab = NULL;
    ui_TouchNextbtn = NULL;
    ui_TouchNextlab = NULL;
    ui_TouchTestBtn = NULL;
    ui_TouchTestLab = NULL;

}
