// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP-C5-Firmware

#ifndef UI_TOUCHSCREEN_H
#define UI_TOUCHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TouchScreen
extern void ui_TouchScreen_screen_init(void);
extern void ui_TouchScreen_screen_destroy(void);
extern lv_obj_t * ui_TouchScreen;
extern lv_obj_t * ui_TouchTitlelab;
extern lv_obj_t * ui_TouchTiplab;
extern lv_obj_t * ui_TouchPanel;
extern lv_obj_t * ui_TouchSuclab;
extern void ui_event_TouchNextbtn(lv_event_t * e);
extern lv_obj_t * ui_TouchNextbtn;
extern lv_obj_t * ui_TouchNextlab;
extern void ui_event_TouchTestBtn(lv_event_t * e);
extern lv_obj_t * ui_TouchTestBtn;
extern lv_obj_t * ui_TouchTestLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

